### ISSUE TITLE
EXC_BAD_ACCESS Error Message

### ISSUE THREAD

**Issue by InspiringPeople** [brangerbriz/t-SNEPointSelector#5]
Hi, brangerbriz!

I solved the problem. It's occurred by the absence of some midi files so that it doesn't match files and .json points. I closed the issue, Thank you.

...........................................................................................................................
I build t-SNEPointSelector well, but when I click a point (midi file) the error message occurred.

Thread 1: EXC_BAD_ACCESS (code=1, address=0x29970)

File name : DataHandler.cpp 
string DataHandler::getMidiIdentifier(int index)
{
    return _fileIdentifiers[index];
}

Do you have any idea about this?
Your help will be very helpful. Thanks in advance.

**Comment by nbriz** [comment]
hmmm, @brannondorsey any ideas?

**Comment by InspiringPeople** [comment]
I solved the problem. It's occurred by the absence of some midi files so that it doesn't match files and .json points. I closed the issue, Thank you.
